#!/bin/bash

# export ANSICON=true
# export TERM=msys
# C:\Public\SOFTWARE\cmderrs\cmder_mini-1.3.8\vendor\conemu-maximus5\ConEmu\conemu-msys2-64.exe  /usr/bin/bash.exe -c "./echos"

depth=0
okcols="42;97"
infocols="46;97"
warncols="43;30"
errorcols="45;97"
fatalcols="41;97"
pcol="\e["
scol="\e[0m"
mcol="m"
# echo "FROM_DOS='${FROM_DOS}'"
if [[ "${FROM_UNIX}" != "" ]]; then
  infocols="106;30"
  warncols="103;30"
  errorcols="101;30"
fi
if [[ "${NOCOLORS}" != "" ]]; then
  okcols=""
  infocols=""
  warncols=""
  errorcols=""
  fatalcols=""
  pcol=""
  scol=""
  mcol=""
fi
function mlog() { if [[ "${2}" != "" ]]; then eval "${2}=\"\${${2}}\n\${1}\""; fi; }
function spaces() { if [[ ${depth} -gt 0 ]]; then printf %${depth}s; fi; }
function ok() { spaces; echo -e "${pcol}${okcols}${mcol} Ok    ${scol}: ${1}"; mlog "ok: ${1}" "${2}"; }
function info() { spaces; echo -e "${pcol}${infocols}${mcol} Info  ${scol}: ${1}"; mlog "info: ${1}" "${2}"; }
function warning() { spaces; echo -e "${pcol}${warncols}${mcol} Warn  ${scol}: ${1}"; mlog "Warning: ${1}" "${2}"; }
function error() { spaces; echo -e "${pcol}${errorcols}${mcol} Error ${scol}: ${1}"; mlog "ERROR: ${1}" "${2}"; }
function fatal() { spaces; echo -e "${pcol}${fatalcols}${mcol} FATAL ${scol}: ${1}"; exit "${2}"; mlog "FATAL: ${1}" "${3}"; }

# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
(return 0 2>/dev/null) && sourced=1 || sourced=0
if [[ "${1}" == "" && ${sourced} -eq 0 ]]; then
  # echo "TERM='${TERM}', ANSICON='${ANSICON}'"
  ok "test bash msg"
  info "test bash msg"
  warning "test bash msg"
  error "test bash msg"
  fatal "test bash msg" 1
fi